const wordList = [
{ word: "blue", hint: "Color of the sky on a clear day" },
{ word: "tree", hint: "Tall plant with a trunk and branches" },
{ word: "apple", hint: "A fruit that is often red or green" },
{ word: "bird", hint: "Feathered creature that can fly" },
{ word: "cake", hint: "Sweet dessert often served at celebrations" },
{ word: "rock", hint: "Solid mineral material forming part of the surface of the Earth" },
{ word: "mouse", hint: "Small rodent often found in houses" },
{ word: "dance", hint: "Movement to music" },
{ word: "light", hint: "What allows us to see things" },
{ word: "happy", hint: "Feeling of joy and contentment" },
{ word: "cloud", hint: "White fluffy mass in the sky" },
{ word: "water", hint: "Clear liquid essential for life" },
{ word: "green", hint: "Color of grass and leaves" },
{ word: "smile", hint: "Facial expression indicating happiness or amusement" },
{ word: "sunny", hint: "Weather condition with bright sunlight" },
{ word: "heart", hint: "Organ that pumps blood through the circulatory system" },
{ word: "pizza", hint: "Popular Italian dish with melted cheese and toppings" },
{ word: "river", hint: "Natural flowing watercourse" },
{ word: "night", hint: "Period of darkness between sunset and sunrise" },
{ word: "phone", hint: "Device used for communication over long distances" },
{ word: "music", hint: "Art form consisting of sound and silence" },
{ word: "bread", hint: "Basic food made from flour, water, and yeast" },
{ word: "tiger", hint: "Large carnivorous feline with distinctive stripes" },
{ word: "lemon", hint: "A key ingredient in Lemonade"},
{word: "brush", hint: "An action you should do every morning to have clean teeth"},
{ word: "banana", hint: "Yellow fruit with a curved shape" },
  { word: "cactus", hint: "Plant adapted to hot, dry climates with thick stems and spines" },
  { word: "donkey", hint: "Domesticated hoofed mammal known for its braying sound" },
  { word: "eagle", hint: "Large bird of prey with a hooked beak and keen eyesight" },
  { word: "flute", hint: "Musical instrument made of a tube with holes, played by blowing across a hole" },
  { word: "garden", hint: "Area of land where plants, flowers, and vegetables are grown" },
  { word: "hammer", hint: "Tool with a heavy head on a handle, used for pounding nails or breaking things" },
  { word: "island", hint: "Landmass surrounded by water on all sides" },
  { word: "jacket", hint: "Outer garment worn on the upper body, typically with sleeves and a fastening down the front" },
  { word: "koala", hint: "Marsupial native to Australia with a distinctive nose and thick fur" },
  { word: "lizard", hint: "Reptile with a long body, four legs, and a tail" },
  { word: "mango", hint: "Tropical fruit with a sweet, juicy flesh and a large seed in the center" },
  { word: "ninja", hint: "Skilled warrior trained in ninjutsu, a Japanese martial art" },
  { word: "orchid", hint: "Flowering plant with complex and often colorful blooms" },
  { word: "puzzle", hint: "Game or toy designed to test ingenuity or knowledge" },
  { word: "rocket", hint: "Projectile or vehicle propelled by an engine, typically used for space travel" },
  { word: "sunset", hint: "Daily event where the sun disappears below the horizon" },
  { word: "tulip", hint: "Spring-flowering plant with brightly colored cup-shaped flowers" },
  { word: "umbrella", hint: "Device used for protection against rain or sunlight, consisting of a collapsible canopy" },
  { word: "violin", hint: "Stringed musical instrument played with a bow" },
  { word: "whale", hint: "Large marine mammal with a streamlined body and a blowhole for breathing" },
  { word: "yacht", hint: "Recreational boat used for cruising or racing on water" },
  { word: "avocado", hint: "Green fruit with a large seed and creamy flesh" },
  { word: "butter", hint: "Dairy product made by churning cream or milk" },
  { word: "carousel", hint: "Merry-go-round ride with seats suspended from a rotating platform" },
  { word: "diamond", hint: "Precious gemstone made of crystallized carbon" },
  { word: "elephant", hint: "Large mammal with a long trunk and tusks" },
  { word: "fireworks", hint: "Explosive pyrotechnic devices used for entertainment or celebration" },
  { word: "giraffe", hint: "Tall African mammal with a long neck and spotted coat" },
  { word: "hurricane", hint: "Powerful tropical storm with strong winds and heavy rain" },
  { word: "iceberg", hint: "Large floating mass of ice detached from a glacier or ice sheet" },
  { word: "jigsaw", hint: "Tool with a toothed blade used for cutting curved or irregular shapes" },
  { word: "kangaroo", hint: "Marsupial native to Australia with large hind legs for jumping" },
  { word: "lighthouse", hint: "Tall tower with a bright light used to guide ships at sea" },
  { word: "magnet", hint: "Object with a magnetic field that attracts certain metals" },
  { word: "noodle", hint: "Long, thin strip of dough, typically made from flour, water, and eggs" },
  { word: "octopus", hint: "Marine mollusk with eight flexible arms and a soft, bulbous body" },
  { word: "penguin", hint: "Flightless bird native to the Southern Hemisphere, known for its black and white plumage" },
  { word: "quicksand", hint: "Saturated sand with water that cannot support weight, often found in marshes or near rivers" },
  { word: "rainbow", hint: "Optical and meteorological phenomenon caused by reflection, refraction, and dispersion of light" },
  { word: "sunflower", hint: "Tall, yellow-flowered plant with seeds that are often eaten as a snack" },
  { word: "tornado", hint: "Violently rotating column of air extending from a thunderstorm to the ground" },
  { word: "unicorn", hint: "Mythical creature resembling a horse with a single horn on its forehead" },
  { word: "volcano", hint: "Opening in the Earth's crust through which lava, ash, and gases erupt" },
  { word: "yogurt", hint: "Dairy product made by fermenting milk with bacterial cultures" },
  { word: "zebra", hint: "African mammal with black and white stripes" },
]